media: uploads
content:
  - name: posts
    label: Posts
    type: collection
    path: '_posts'
    view:
      fields: [ title, published, date ]
    fields:
      - name: layout
        hidden: true
        type: string
        default: "post"
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: date
        label: Date
        type: date
        options:
          format: "yyyy-MM-dd' 'HH:mm:ss"
          time: true
      - name: image
        label: Image
        type: image
      - name: excerpt
        label: Excerpt
        type: text
      - name: tags
        label: Tags
        list: true
        type: string
      - name: author
        label: Author
        type: string
        required: true
      - name: redirect_from
        label: Redirects
        list: true
        type: string
      - name: published
        label: Published
        type: boolean
        default: true