# Site settings
title: Pão com Mortadela
tagline: >-
  Uma dica bacana para acompanhar seu café.
description: |+
  Tem tanta coisa por aí.  
  A gente te ajuda a encontrar aquilo que você vai gostar.  
  Algo bom pra ler, ver, ouvir ou jogar.

lang: pt-BR
logo: "/assets/images/logo.png"
timezone: America/Sao_Paulo

collections:
  links:
    output: false


# Build settings
markdown: kramdown
url: 'https://paomortadela.com.br' # mudar no merge
baseurl: ''

permalink: /:year/:month/:title/
paginate: 8
paginate_path: "/p:num/"

include:
  - _redirects
  - _prose.yml
  
keep_files:
  - ads.txt
  - assets/img
  - assets/js
  - uploads

collections:
  authors:
    output: true
    permalink: "/autor/:title/"

defaults:
  - scope:
      path: ''
    values:
      image: "/assets/images/default.jpg"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-include-cache
  

# SEO
social:
  name: Pão com Mortadela
  links:
    - https://twitter.com/paomortadela
    - https://www.facebook.com/paomortadela.com.br
    - https://tinyletter.com/paomortadela

twitter:
  username: paomortadela
  card: summary_large_image


# Archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    tag: "/tag/:name/"

# CMS
prose:
  rooturl: ""
  siteurl: "https://paomortadela.com.br"
  media: "/uploads"
  relativeLinks: "https://paomortadela.com.br/assets/lists/links.jsonp"
  ignore:
    - _includes/
    - _layouts/
    - _sass/
    - assets/
    - .editorconfig
    - .gitattributes
    - .gitignore
    - .lfsconfig
    - 404.md
    - Gemfile
    - LICENSE
    - _redirects
    - ads.txt
    - favicon.ico
    - readme.md
  metadata:
    _posts:
      - name: layout
        field:
          element: hidden
          value: post
      - name: title
        field:
          element: text
          label: Title
      - name: date
        field:
          element: text
          label: Date
          value: CURRENT_DATETIME
      - name: image
        field:
          element: text
          label: Image
      - name: author
        field:
          element: select
          label: Author
          value: arthurf
          options: "https://paomortadela.com.br/assets/lists/authors.jsonp?callback=authorsCallback"
      - name: tags
        field:
          element: multiselect
          label: Tags
          value: resenhas
          options: "https://paomortadela.com.br/assets/lists/tags.jsonp?callback=tagCallback"
          alterable: true
      - name: published
        field:
          element: checkbox
          label: Publish?
          value: true
    _links:
      - name: title
        field:
          element: text
          label: Title
      - name: date
        field:
          element: hidden
          value: CURRENT_DATETIME
      - name: published
        field:
          element: hidden
          value: true
      - name: permalink
        field:
          element: text
          label: Link URL
