encoding: UTF-8

title: Pão com Mortadela
url: 'http://paomortadela.com.br'
baseurl: ''
description: >
  Todos os dias uma sugestão de livro, filme, música, série, jogo ou link. Sempre uma coisa boa, pra deixar seu dia melhor, mais divertido e mais ~cult~.

disqus: paomortadela
analytics: UA-71750920-3
lang: pt

contact:
  email: padeiros@paomortadela.com.br
  facebook: paocomortadela
  github: arthrfrts/pcm
  twitter: paomortadela

markdown: kramdown
permalink: /:title.html

theme: minima

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
