# Site settings
title: Pão com Mortadela
tagline: >-
  Uma dica bacana para acompanhar seu café.
description: |+
  Tem tanta coisa por aí.  
  A gente te ajuda a encontrar aquilo que você vai gostar.  
  Algo bom pra ler, ver, ouvir ou jogar.

lang: pt-BR
logo: "/assets/images/logo.png"
timezone: America/Sao_Paulo


# Build settings
incremental: true
markdown: kramdown
url: 'https://paomortadela.com.br'
baseurl: ''

permalink: /:year/:month/:title/
paginate: 12
paginate_path: "/p:num/"

include:
  - _redirects
  
keep_files:
  - assets/img
  - assets/js
  - uploads

defaults:
  - scope:
      path: ''
    values:
      image: "/assets/images/default.jpg"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate
  - jekyll-coffeescript
  - jekyll-include-cache
  

# SEO
social:
  name: Pão com Mortadela
  links:
    - https://twitter.com/paomortadela
    - https://www.facebook.com/paomortadela.com.br
    - https://tinyletter.com/paomortadela

twitter:
  username: paomortadela
  card: summary_large_image


# Archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    tag: "/tag/:name/"
