# Site settings
title: Pão com Mortadela
tagline: >-
  Uma dica bacana para acompanhar seu café.
description: |+
  Tem tanta coisa por aí.  
  A gente te ajuda a encontrar aquilo que você vai gostar.  
  Algo bom pra ler, ver, ouvir ou jogar.

lang: pt-BR
logo: "/assets/images/logo.png"
timezone: America/Sao_Paulo

collections:
  notes:
    output: false
  authors:
    output: true
    permalink: "/arquivo/autor/:title/"

# Build settings
markdown: kramdown
incremental: true

url: "https://paomortadela.com.br" # mudar no merge
baseurl: ""

permalink: /:year/:month/:title/
paginate: 8
paginate_path: "/arquivo/pagina/:num/"
seo_paginator_message: "Página %<current>s de %<total>s | "

include:
  - _redirects
  - _headers

keep_files:
  - ads.txt
  - assets/images
  - assets/js
  - uploads

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-paginate

# SEO
social:
  name: Pão com Mortadela
  links:
    - https://twitter.com/paomortadela
    - https://www.facebook.com/paomortadela.com.br

twitter:
  username: paomortadela
  card: summary_large_image

# Archives
jekyll-archives:
  enabled:
    - tags
    - year
    - month
  layout: "archive"
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    tag: "/arquivo/:name/"
