title: Pão com Mortadela
url: 'https://paomortadela.com.br'
baseurl: ''
description: >
  Todos os dias postamos uma sugestão de livro, filme, música, série, jogo ou link. Sempre uma coisa boa, pra deixar sua semana melhor e mais divertida.

disqus: paomortadela
lang: pt

email: email@arthr.me
facebook: paocomortadela
github: arthrfrts/pcm
twitter: paomortadela

colections:
  uploads:
    output: true
    permalink: "/assets/media/:path"

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: arthrfrts

markdown: kramdown
permalink: /:year/:slug.html
paginate: 4

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

exclude:
  - LICENSE
  - Gemfile
  - Gemfile.lock
