# Site settings
title: Pão com Mortadela
description: >
  Sempre algo bacana pra ler na hora do café.
lang: pt-BR
timezone: America/Sao_Paulo

contact:
  facebook: paomortadela.com.br
  twitter: paomortadela

author:
  name: Arthur Freitas
  uri: https://arthr.me/
  twitter: arthrfrts

# Content settings
collections:
  svg:
    output: false

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post

# Build settings
url: 'https://paomortadela.com.br'
baseurl: ''

markdown: kramdown
permalink: /post/:year/:title/

pagination:
  enabled: true
  per_page: 5
  permalink: '/arquivos/parte/:num/'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'archive.html'
    permalink: '/arquivos/secao/:cat/'
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - 'archive.html'
    permalink: '/arquivos/tag/:tag/'

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jemoji

source: _source
