# Site settings
title: Pão com Mortadela
description: >
  Algo bacana pra ler na hora do café.
lang: pt-BR

# Content settings
contact:
  facebook: paomortadela.com.br
  twitter: paomortadela

collections:
  svg:
    output: false

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: arthr

# Build settings
url: 'https://paomortadela.com.br'
baseurl: ''

markdown: kramdown
permalink: /:year/:name/

pagination:
  enabled: true
  per_page: 9
  permalink: '/parte/:num/'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    enabled: true
    layouts:
      - 'archive.html'
    permalink: '/arquivos/:cat/'
  collections:
    enabled: false
  tags:
    enabled: true
    layouts:
      - 'archive.html'
    permalink: '/arquivos/tags/:tag/'

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jemoji

source: _source
