# Site settings
title: Pão com Mortadela
description: >
  Sempre uma coisa boa pra ler na hora do café.

lang: pt
timezone: America/Sao_Paulo
logo: "/assets/images/logo.png"

email: padeiros@paomortadela.com.br
facebook_username: "paomortadela.com.br"
twitter_username: "paomortadela"


# Build settings
url: 'https://paomortadela.com.br'
baseurl: ''

markdown: kramdown
permalink: /:year/:title/

paginate: 8
paginate_path: '/pagina/:num/'

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: "archive"
  permalinks:
    category: "/categoria/:name/"
    tag: "/tag/:name/"

google_site_verification: "UfVsLDHK_53R85Kjji9NyyMbgE5Le9qjtkEVnD7TQWE"

# Prose settings
prose:
  rooturl: "_posts"
  siteurl: "https://paomortadela.com.br/"
  relativeLinks: "https://paomortadela.com.br/lists/links.jsonp"
  media: "assets/uploads"
  ignore:
    - "/_includes"
    - "/_layouts"
    - "/_sass"
    - "_config.yml"
    - "LICENSE"
    - "Gemfile"
    - "Gemfile.lock"
    - "index.html"
    - "readme.md"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "date"
        field:
          element: "hidden"
          label: "Date"
          value: CURRENT_DATETIME
      - name: "image"
        field:
          element: "text"
          label: "Image"
          value: "/assets/images/ogp.jpg"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options: "https://paomortadela.com.br/assets/lists/categories.jsonp"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          options: "https://paomortadela.com.br/lists/tags.jsonp"
          alterable: true
      - name: "author"
        field:
          element: "text"
          label: "Author(s)"
          value: ""    

defaults:
- scope:
    path: ''
  values:
    image: "/assets/images/ogp.jpg"
- scope:
    path: ''
    type: posts
  values:
    seo:
      type: "BlogPosting"

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-compose
  - jekyll-paginate
  - jekyll-archives