# Site settings
title: Pão com Mortadela
description: >
  Sempre uma coisa boa pra ler na hora do café.

lang: pt
timezone: America/Sao_Paulo
logo: "/assets/images/logo.png"

email: padeiros@paomortadela.com.br
facebook_username: "paomortadela.com.br"
twitter_username: "paomortadela"


# Build settings
url: 'https://paomortadela.com.br'
baseurl: ''

markdown: kramdown
permalink: /:year/:title/

paginate: 12
paginate_path: '/pagina/:num/'

jekyll-archives:
  enabled:
    - tags
    - categories
  layout: "archive"
  permalinks:
    category: "/categoria/:name/"
    tag: "/tag/:name/"

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: arthur

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-archives
  - jekyll-coffeescript

source: _source
