# Site settings
title: Pão com Mortadela
description: >
  Algo bacana pra ler na hora do café.
lang: pt-BR

# Content settings
contact:
  facebook: paomortadela.com.br
  twitter: paomortadela

collections:
  svg:
    output: false

defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    author: arthr

# Build settings
url: 'https://paomortadela.com.br'
baseurl: ''

markdown: kramdown
permalink: /:year/:name/
paginate: 10

plugins:
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives
  - jemoji

source: _source
