encoding: UTF-8

title: Pão com Mortadela
url: 'http://paomortadela.com.br'
baseurl: ''
description: >
  Toda segunda e quinta postamos uma sugestão de livro, filme, música, série, jogo ou link. Sempre uma coisa boa, pra deixar sua semana melhor e mais divertida.

disqus: paomortadela
analytics: UA-71750920-3
lang: pt

contact:
  email: padeiros@paomortadela.com.br
  facebook: paocomortadela
  github: arthrfrts/pcm
  twitter: paomortadela

markdown: kramdown
permalink: /:slug.html
paginate: 5

theme: minima

gems:
  - jekyll-sitemap
  - jemoji
  - jekyll-paginate
