---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - post
- type: directory
  path: _notes
  label: Notes
  create: all
  match: "**/*"
  new_doc_ext: ".txt"
  templates:
  - note
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - page
- type: heading
  label: Authors
- type: document
  path: _data/authors.yml
  label: Authors
  read_only: true
- type: directory
  path: _authors
  label: Archives
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  - GIT_LFS_SKIP_SMUDGE=1
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
